### ISSUE TITLE
Zadania Zad1, Zad2 itd.

### ISSUE THREAD

**Issue by trzczy** [migellal/KenisKursJava#1]
Dlaczego te zadania, np. **KenisKursJava/8/out/production/8/Zad3/Main.class**, nie są dostępne? Można je jakoś otworzyć, obejrzeć? Oczywiście chodziłoby mi o odpowedzi do zadań.

**Comment by migellal** [comment]
Kod dostępny jest w katalogach src, np:
https://github.com/migellal/KenisKursJava/tree/master/2/src
